version '3.1'

services:

  db:
    image: mariadb:10.3
    env_file:
      - ./glpi.env
    container_name: db
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - glpinet
    placement:
      constraints: [node.role == manager]

  glpi:
    image: churrops/glpi
    env_file:
      - ./glpi.env
    ports:
      - 80:80
    networks:
      - glpinet
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

network:
  glpinet:
  
volumes:
  db-data
  glpi-data
