version: '2'

services:
  db:
    image: mariadb:10.3
    container_name: db
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: glpi
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    ports:
      - "3306"
    networks:
      - glpinet

  glpi:
    depends_on:
      - db
    image: churrops/glpi
    ports:
      - "80:80"
    restart: always
    networks:
      - glpinet
    links:
      - db

networks:
  glpinet:
  
volumes:
  db-data:
  glpi-data:
