version '3.1'

services:

  db:
    image: mariadb:10.3
    env_file:
      - ./glpi.env
    container_name: db
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - glpinet

  glpi:
    image: churrops/glpi
    env_file:
      - ./glpi.env
    ports:
      - 80:80
    networks:
      - glpinet
    depends_on:
      - db
    links:
      - db

network:
  glpinet:
  
volumes:
  db-data
  glpi-data
