version: '2'

services:
  db-glpi:
    image: mariadb:10.3
    container_name: db-glpi
    volumes:
      - db-data-glpi:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    ports:
      - "3306"
    networks:
      - glpinet

  db-ocs:
    image: mariadb:10.3
    container_name: db-ocs
    volumes:
      - db-data-ocs:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ocsweb
      MYSQL_USER: ocs
      MYSQL_PASSWORD: ocs
    ports:
      - "3306"
    networks:
      - glpinet

  glpi:
    depends_on:
      - db-glpi
    image: churrops/glpi
    ports:
      - "80:80"
    restart: always
    networks:
      - glpinet
    links:
      - db-glpi

  ocs:
    #image: ocsinventory/ocsinventory-docker-image:2.3.1
    image: rdglinux/ocs
    depends_on:
      - db-ocs
    ports:
      - "8989:80"
    environment:
      OCS_DBNAME: ocsweb 
      OCS_DBSERVER_READ: db-ocs 
      OCS_DBSERVER_WRITE: db-ocs
      OCS_DBUSER: ocs 
      OCS_DBPASS: ocs 

    volumes :
      - ocs-data:/usr/share/ocsinventory-reports/
    networks:
      - glpinet
    links:
      - db-ocs

networks:
  glpinet:
  
volumes:
  db-data-glpi:
  db-data-ocs:
  glpi-data:
  ocs-data:
